### ISSUE TITLE
Bug in handling the "c" family types

### ISSUE THREAD

**Issue by bhazelton** [Center-for-Women-s-Welfare/SSS#13]
In the `data_folder_to_database` function, we create the `weighted_child_count` column and set it equal to the `infant` column. Then we iterate through the rows and if "c" is not in the `family_type`, we set the `weighted_child_count` to np.nan. This is all good. However, on rows that have "c" in the `family_type`, we need to update the `infant` column to be set to zero.

Here's the location of the problem:
https://github.com/Center-for-Women-s-Welfare/SSS/blob/4aebacbe6d9caf5931ac4a12406845a539c23103/sss/sss_table.py#L285

**Comment by HectorSo20** [comment]
This was solved in my pull request.
